### ISSUE TITLE
copy paste error, variable z should be w

### ISSUE THREAD

**Issue by seblabbe** [fredrik-johansson/calcium#1]
https://github.com/fredrik-johansson/calcium/blob/c69f42620ae9acf59737e8bf8efaba123f3de5c8/qqbar/test/t-sec_pi.c#L57

**Comment by seblabbe** [comment]
Fredrik, I was just reading randomly some files in your repo after the post on sage-devel, and I saw that typo.

**Comment by fredrik-johansson** [comment]
Fixed. Thanks for reporting!

**Comment by seblabbe** [comment]
It seems the error occurs in other file, for example:
https://github.com/fredrik-johansson/calcium/blob/3016654129679b83f4a62066244a69697d14971b/qqbar/test/t-cos_pi.c#L54
I did not check further.

**Comment by fredrik-johansson** [comment]
Indeed. Should all be fixed now.
