### ISSUE TITLE
Configure script

### ISSUE THREAD

**Issue by SnarkBoojum** [fredrik-johansson/calcium#10]
I was pondering packaging calcium for Debian (experimental at first, since it isn't considered stable yet). I noticed the configure script doesn't go with the rest of the files : it comes from flint & arb, but there it is GPL-2+ -- so I think you should make it more precise in the code.

**Comment by fredrik-johansson** [comment]
Sounds like a misunderstanding? The configure script should be LGPL along with all other Flint files.

**Comment by SnarkBoojum** [comment]
Oohhh... we hadn't noticed the license change! I'll update the Debian packages accordingly! Indeed let's close this report. Thanks!
