### ISSUE TITLE
Useless rpath setting?

### ISSUE THREAD

**Issue by SnarkBoojum** [fredrik-johansson/calcium#26]
When I leave the rpath settings in the configure script, the Debian checkers complain about the package, so I'm patching them out. I'll attach a patch.

**Comment by SnarkBoojum** [comment]
Here it is:
[no_rpath.txt](https://github.com/fredrik-johansson/calcium/files/6435657/no_rpath.txt)

**Comment by fredrik-johansson** [comment]
We have this line in the Flint and Arb configures. What is different here?

**Comment by SnarkBoojum** [comment]
You mean like I reported [here](https://github.com/fredrik-johansson/arb/issues/232) ?

**Comment by fredrik-johansson** [comment]
Done in 4644e78eb598d0a186cb8914fc18df4d1522f05c.
