### ISSUE TITLE
Binder link broken due to C++ style comment in antic/nf.h?

### ISSUE THREAD

**Issue by bjodah** [fredrik-johansson/calcium#37]
Tried to launch the binder notebook, got the following error in the log:
```console
    CC   ../build/qqbar/neg.lo
    CC   ../build/qqbar/evaluate_fmpq_poly.lo
    CC   ../build/qqbar/validate_enclosure.lo
    CC   ../build/qqbar/init.lo
In file included from evaluate_fmpq_poly.c:12:0:
/srv/conda/envs/notebook/include/antic/nf.h:40:1: error: C++ style comments are not allowed in ISO C90
 // Visibility Macros to separate API from non-API and inline template code.
 ^
/srv/conda/envs/notebook/include/antic/nf.h:40:1: error: (this will be reported only once per input file)
../Makefile.subdirs:60: recipe for target '../build/qqbar/evaluate_fmpq_poly.lo' failed
make[2]: *** [../build/qqbar/evaluate_fmpq_poly.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/home/jovyan/qqbar'
Makefile:121: recipe for target 'libcalcium.so.0.4.1' failed
make[1]: Leaving directory '/home/jovyan'
make[1]: *** [libcalcium.so.0.4.1] Error 2
make: *** [library] Error 2
Makefile:142: recipe for target 'library' failed
```

but looking at https://github.com/wbhart/antic/blame/trunk/nf.h shows no such comment in the current git version of antic. It looks like the binder link uses conda-forge as a source of antic, so I suspect one could either patch the build script or ask for a new release of antic?

**Comment by fredrik-johansson** [comment]
The // comment appears in the conda version, but I can't find it in any version of nf.h in the antic repository, so perhaps it's an incorrect patch being applied in conda-forge.

@isuruf @saraedum any ideas?

**Comment by isuruf** [comment]
It's coming from https://github.com/conda-forge/antic-feedstock/blob/master/recipe/0001-set-dllexport-dllimport-when-building-for-Windows.patch

**Comment by saraedum** [comment]
Sorry for that, it will be fixed in https://github.com/conda-forge/antic-feedstock/pull/8.
