### ISSUE TITLE
Two algebraic numbers comparing equal using qqbar_t yield T_UNKNOWN when comparing them using ca_t

### ISSUE THREAD

**Issue by michiel-dewilde** [fredrik-johansson/calcium#45]
Hi Fredrik,

Thanks for developing calcium! Even in 0.x status it is the better choice for some developments, so I started using it.
I did find an issue though... two algebraic numbers comparing equal using qqbar_t yield T_UNKNOWN when comparing them using ca_t.

The test [t-ca_equality_20221220.c](https://github.com/fredrik-johansson/calcium/files/10276777/t-ca_equality_20221220.c.txt) reproduces the issue.
Calcium version used: commit [59a61324a9a113e269d646691a59273b7e784d04](https://github.com/fredrik-johansson/calcium/commit/59a61324a9a113e269d646691a59273b7e784d04) (current latest on master)
When you find some time, could you have a look?

Thanks and regards,

Michiel

Michiel De Wilde at Keysight Technologies (using my personal GitHub account)

**Comment by fredrik-johansson** [comment]
Probably some evaluation limits are being hit (see https://fredrikj.net/calcium/ca.html#context-options). Try adding something like

    ctx->options[CA_OPT_PREC_LIMIT] = 1000000;
    ctx->options[CA_OPT_QQBAR_DEG_LIMIT] = 10000;

**Comment by michiel-dewilde** [comment]
Many thanks for the quick response!
Indeed the evaluation limits were the issues.

FYR, exact lower boundaries for these limits that make this test work:
```
ctx->options[CA_OPT_PREC_LIMIT] = 5015;
ctx->options[CA_OPT_QQBAR_DEG_LIMIT] = 64;
```

Thanks and regards,

Michiel
